swagger: '2.0'
info:
  version: 1.0.0
  title: WolfLearning
  description: Serviço gerenciador de conteudo, Cursos e Aulas
host: localhost:8080
schemes:
  - http
paths:
  /cadastrar:
    post:
      tags:
        - Cadastrar Curso
      operationId: SalvarCurso
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/CursoModel'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Erro'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Erro'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Erro'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Erro'
      security:
        - OAuth2: []

securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    tokenUrl: 'localhost:8091/auth/oauth/v2/token-jwt'
    authorizationUrl: 'localhost:8091/v1/openid/connect/jwks.json'
    scopes: {}

definitions:
  CursoModel:
    type: array
    items:
      type: object
      properties:
        nome:
          type: string
        categoria:
          type: integer
          format: int64
        data:
          type: string

    required:
      - nome
      - categoria

  Erro:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
        example: erro de validacao