swagger: "2.0"
info:
  description: "serviço de gerenciamento de curso"
  version: "1.0.0"
  title: "Wolf Learning"
host: "localhost:8080"
basePath: "/content-manager"
schemes:
  - "https"
  - "http"
paths:

  /buscar-curso{idCurso}:
    get:
      tags:
        - "Obter"
      summary: "obter curso"
      description: ""
      produces:
        - application/json
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/returnModel"
        "405":
          description: "Invalid input"
        "404":
          description: "Not found"
        "500":
          description: "Internal server error"
      security:
        - OAuth2: []
    parameters:
      - type: string
        in: path
        name: idCurso
        description: "id do curso desejado"
        required: true
  /cadastrar:
    post:
      tags:
        - "Cadastrar"
      summary: "atualiza lista de amigos"
      description: ""
      parameters:
        - in: "body"
          name: "body"
          description: "objeto de usuario necessario para criacao"
          required: true
          schema:
            $ref: "#/definitions/cursoModel"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/cursoModel"
        "405":
          description: "Invalid input"
        "404":
          description: "Not found"
        "500":
          description: "Internal server error"
      security:
        - OAuth2: []


securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    tokenUrl: "http://localhost:8081/auth"

definitions:
  cursoModel:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      horario:
        type: string
      status:
        type: string
  returnModel:
    type: "object"
    properties:
      code:
        type: integer
      message:
        type: string
