spring:
  application:
    name: content-manager
    description: orquestrador de gerenciamento de conteudos (cursos , aulas)


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8089/auth/realms/wolflearning'
          set-uri: 'http://localhost:8089/auth/realms/wolflearning/protocolo/openid-connect/certs'
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG